# Site settings
title: OSGi™ enRoute - The OSGi™ Alliance
email: Peter.Kriens@aQute.biz
description: > # this means to ignore newlines until "baseurl:"
  OSGi™ enRoute is an OSGi™ Alliance project. It's purpose is to streamline the process of utilizing OSGi structure within java systems through tool chain enhancements, service-based libraries and education.
baseurl: "/osgi.enroute.site.gh-pages" # the subpath of your site, e.g. /blog/
url: "http://enroute.osgi.org" # the base hostname & protocol for your site
twitter_username: OSGiAlliance
github_username: osgi

# Build settings
markdown: kramdown

collections:
  book:
    output: true
  qs:
    output: true
  tutorial_base:
    output: true
  services:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
